/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class JCheckBox extends javax.swing.JFrame {

    /**
     * Creates new form JCheckBox
     */
    public JCheckBox() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(rbtFemale);
        bg.add(rbtMale);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGioiTinh = new javax.swing.JLabel();
        rbtMale = new javax.swing.JRadioButton();
        rbtFemale = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cbMusic = new javax.swing.JCheckBox();
        cbMovie = new javax.swing.JCheckBox();
        btnOK = new javax.swing.JButton();
        btnDefault = new javax.swing.JButton();
        cbbtnHocVan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGioiTinh.setText("Giới tính");

        rbtMale.setText("Nam");

        rbtFemale.setText("Nữ");

        jLabel2.setText("Sở thích");

        cbMusic.setText("Âm nhạc");

        cbMovie.setText("Phim");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnDefault.setText("Mặc định");
        btnDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefaultActionPerformed(evt);
            }
        });

        cbbtnHocVan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trình độ học vấn", "Tiến sĩ", "Thạc sĩ", "Khác" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbtnHocVan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDefault))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(cbMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtMale)
                        .addGap(62, 62, 62)
                        .addComponent(rbtFemale)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtMale)
                    .addComponent(rbtFemale))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMusic)
                    .addComponent(cbMovie))
                .addGap(18, 18, 18)
                .addComponent(cbbtnHocVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDefault))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
//        if(rbtFemale.isSelected()){
//            JOptionPane.showMessageDialog(null, "Giới tính của bạn là Nữ");
//        }else{
//            JOptionPane.showMessageDialog(null, "Giới tính của bạn là Nam");
//        }
//        if(cbMusic.isSelected()){
//            JOptionPane.showMessageDialog(null, "Sở thích cảu bạn là âm nhạc");
//        }
//        if(cbMovie.isSelected()){
//            JOptionPane.showMessageDialog(null, "Sở thích cảu bạn là phim");
//        }
//lấy ra giá trị cảu box
            String hocVan = cbbtnHocVan.getSelectedItem().toString();
            if(!rbtFemale.isSelected()&& !rbtMale.isSelected()){
                JOptionPane.showMessageDialog(null, "Vui lòng chọn giới tính");
                return;
            }
            if(!cbMusic.isSelected()&& !cbMovie.isSelected()){
                JOptionPane.showMessageDialog(null, "Vui lòng chọn sở thích");
                return;
            }
//            mỗi dòng được tổ chức dưới dạng index
//kiểm tra coi mục mình chọn có phải là mục ban đầu(mặc định)
            if(cbbtnHocVan.getSelectedIndex()<=0){
                JOptionPane.showMessageDialog(null, "Vui lòng chọn học vấn");
                return;
            }
            JOptionPane.showMessageDialog(null, "Dữ liệu hợp lệ");
              
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefaultActionPerformed
        // TODO add your handling code here:
        rbtMale.setSelected(true);
        cbMusic.setSelected(false);
        cbMovie.setSelected(false);

        
    }//GEN-LAST:event_btnDefaultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCheckBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDefault;
    private javax.swing.JLabel btnGioiTinh;
    private javax.swing.JButton btnOK;
    private javax.swing.JCheckBox cbMovie;
    private javax.swing.JCheckBox cbMusic;
    private javax.swing.JComboBox<String> cbbtnHocVan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbtFemale;
    private javax.swing.JRadioButton rbtMale;
    // End of variables declaration//GEN-END:variables
}
